### ISSUE TITLE
Charging Image shown when truck not charging

### ISSUE THREAD

**Issue by haugenc** [tmack8001/ha-rivian-card#11]
from rivian-charging-card.yml: 167-174

>   '- type: conditional
    conditions:
      - entity: binary_sensor.maeve_charger_connection
        state_not: "on"
    card:
      type: picture-elements
      image: >-
        https://github.com/tmack8001/ha-rivian-card/blob/main/src/images/r1t/side_charging/dark/r1t-launch-green.png?raw=true'

Should this be linked to a side view image not plugged in?
Image is showing a plugged in R1T, when it is not charging

**Comment by tmack8001** [comment]
Probably, though there isn't a great image of the truck/suv from the side without the charging cable. The best you can get from rivian provided images is just the front end (see latest mobile app) and thus then makes it impossible to see a difference between R1T and R1S models.

I will likely add those images to this repo to have them to hold on to, also recently added them to the beta releases of HA so feel free to switch out to those if you prefer.
