### ISSUE TITLE
Global Lock State (binary_sensor.rivian_lock_state)

### ISSUE THREAD

**Issue by tmack8001** [tmack8001/ha-rivian-card#3]
This entity doesn't exist yet as there is an open PR to add it to the HA integration.

That is being proposed by https://github.com/bretterer/home-assistant-rivian/pull/52

**Comment by kalanchoej** [comment]
Glad I found this issue - thought I was going crazy

**Comment by tmack8001** [comment]
Yeah I thought about just changing over to use the lock state of the "driver" door, but that wouldn't be appropriate in all circumstances so decided just to wait until the entity exists and propose an aggregate lock state based on "any closure unlocked"
