### ISSUE TITLE
R1S config doesn't appear to work

### ISSUE THREAD

**Issue by poldim** [tmack8001/ha-rivian-card#9]
Hey,
I tried using [your R1S config](https://github.com/tmack8001/ha-rivian-card/blob/main/src/custom-elements/rivian-r1s-state-card-dependencies.yml) but getting some odd scaling and layout issues.  I have card mod and bar card installed.  At this point, the only change I have is using a white truck and updating the entity id's to remove `rivian_` and updating the battery SOC entity id name to match the current defaults from the integration (v0.9.2).

<img width="954" alt="image" src="https://github.com/tmack8001/ha-rivian-card/assets/16869713/a02d19f6-7e02-49b5-9003-b7890187b174">

**Comment by tmack8001** [comment]
@poldim are you still having these issues with the latest?

I've seen this commonly happen when card-mod isn't installed which allows for CSS to be added to scale down the images that are loaded for the pictures card. Are you positive that is installed?

https://github.com/thomasloven/lovelace-card-mod and see the installation instructions https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins

At http://homeassistant.local:8123/hacs/entry (replacing with your host and port number of your installation) should appear similar to mine with these two lines called out.

<img width="1344" alt="image" src="https://github.com/tmack8001/ha-rivian-card/assets/2158627/9940ebae-c466-4402-8d5d-28b7e1ad704b">
<img width="1345" alt="image" src="https://github.com/tmack8001/ha-rivian-card/assets/2158627/4cd41bc9-4ca1-41e7-be9e-16cec126cc31">

**Comment by tmack8001** [comment]
I just pulled down the current card definition (which I made slight adjustments to recently)

light glacier white R1S
<img width="486" alt="image" src="https://github.com/tmack8001/ha-rivian-card/assets/2158627/86d98767-b507-484b-985d-2d5ed2d1de25">

dark glacier white R1S
<img width="489" alt="image" src="https://github.com/tmack8001/ha-rivian-card/assets/2158627/44715c13-d328-4e8e-9c7f-e0ca14a30d52">

**Comment by poldim** [comment]
> At http://homeassistant.local:8123/hacs/entry (replacing with your host and port number of your installation) should appear similar to mine with these two lines called out.
> 
> <img alt="image" width="1344" src="https://user-images.githubusercontent.com/2158627/260523079-9940ebae-c466-4402-8d5d-28b7e1ad704b.png"> <img alt="image" width="1345" src="https://user-images.githubusercontent.com/2158627/260523096-4cd41bc9-4ca1-41e7-be9e-16cec126cc31.png">

Odd but when I go to TLD/hacs/entry I don't get anything like that.  It just takes me to the HACS "homepage":
<img width="1044" alt="image" src="https://github.com/tmack8001/ha-rivian-card/assets/16869713/86ccad6f-5a67-4b75-84b9-4c4e8d1e22bf">

**Comment by poldim** [comment]
> I just pulled down the current card definition (which I made slight adjustments to recently)
> 
> dark glacier white R1S <img alt="image" width="489" src="https://user-images.githubusercontent.com/2158627/260523388-44715c13-d328-4e8e-9c7f-e0ca14a30d52.png">

How do you set your icon?  I poked around the config and see [this UI element](https://github.com/tmack8001/ha-rivian-card/blob/ecf36258b04777901b0578e5c6987e3cc28e609e/src/custom-elements/rivian-r1s-state-card-dependencies.yml#L314C1-L320C1) and probably [this icon](https://raw.githubusercontent.com/tmack8001/ha-rivian-card/main/src/images/r1s/r1s_badge.webp) but I can't find anything on google explaining how to use a `webp` as an icon.

<img width="510" alt="image" src="https://github.com/tmack8001/ha-rivian-card/assets/16869713/1f9b4f5a-b094-4e6e-9152-57c5e698cb21">

**Comment by poldim** [comment]
Closing per https://community.home-assistant.io/t/generic-vehicle-card/397844/108

**Comment by tmack8001** [comment]
Ah the icon, that is actually the device_tracker icon I setup for myself given I have a R1T and an R1S I preferred the device (in HA) to have the icon of the badges. I played around with side views and front views, but liked the badge better at this point. If I had >2 having unique color profiles probably would make better sense.

**Comment by poldim** [comment]
> Ah the icon, that is actually the device_tracker icon I setup for myself given I have a R1T and an R1S I preferred the device (in HA) to have the icon of the badges. I played around with side views and front views, but liked the badge better at this point. If I had >2 having unique color profiles probably would make better sense.

How do you configure your icon to be the `webp` file?

**Comment by tmack8001** [comment]
Here is my configuration.yaml which I edit with HACS integration called "File Editor"

```
homeassistant:
  customize:
    device_tracker.sully_location:
    #   entity_picture: "/local/r1t_2021_adventure_ext_rivian-blue_20ad1-brit-at_front_dark_large_@2x.png"
      entity_picture: "/local/r1t_badge.webp"
      friendly_name: "R1T"
    device_tracker.mike_location:
    #   entity_picture: "/local/r1s_2021_adventure_ext_launch-green_20ad1-brit-at_front_dark_large_@2x.png"
      entity_picture: "/local/r1s_badge.webp"
      friendly_name: "R1S"
```

`device_tracker.mike_location` or `device_tracker.sully_location` are my device trackers obviously, replace with your vehicle's name or `r1t`/`r1s` as appropriate.
